"""switching price types to biginteger

Revision ID: 245033b403ff
Revises: 3784386eea87
Create Date: 2013-07-09 14:27:26.788757

"""

# revision identifiers, used by Alembic.
revision = '245033b403ff'
down_revision = '3784386eea87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', u'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', u'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
