"""add deposit instructions column

Revision ID: 2d001f91219a
Revises: 258641a695a4
Create Date: 2014-05-17 15:48:23.052299

"""

# revision identifiers, used by Alembic.
revision = '2d001f91219a'
down_revision = '258641a695a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('deposit_instructions', sa.String(), server_default='Please send your crypto-currency to this address', nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'deposit_instructions')
    ### end Alembic commands ###
