"""Generalized final payoff and multiplier field in a contract level denominator field

Revision ID: 3f09d56a958a
Revises: 5344e95e7351
Create Date: 2013-07-09 11:29:55.913016

"""

# revision identifiers, used by Alembic.
revision = '3f09d56a958a'
down_revision = '5344e95e7351'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('denominator', sa.Integer(), server_default='1', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'denominator')
    ### end Alembic commands ###
