"""added cash contract type

Revision ID: 4eb9b769c8c6
Revises: 34951675cc15
Create Date: 2013-07-09 11:41:02.849126

"""

# revision identifiers, used by Alembic.
revision = '4eb9b769c8c6'
down_revision = '34951675cc15'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
