"""added a withdrawal table + other changes

Revision ID: 550dfe04e996
Revises: aa43764a2fd
Create Date: 2013-07-29 15:11:33.571549

"""

# revision identifiers, used by Alembic.
revision = '550dfe04e996'
down_revision = 'aa43764a2fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('pending', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('entered', sa.DateTime(), nullable=False),
    sa.Column('completed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'addresses', u'accounted_for',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=u'0::bigint')
    op.alter_column(u'addresses', u'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'addresses', u'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column(u'addresses', u'accounted_for',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=u'0::bigint')
    op.drop_table('withdrawals')
    ### end Alembic commands ###
