"""switch denominator from int to bigint

Revision ID: 57bb64889856
Revises: 272edafccba4
Create Date: 2013-07-09 11:36:22.700955

"""

# revision identifiers, used by Alembic.
revision = '57bb64889856'
down_revision = '272edafccba4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
