"""adding inverse contract

Revision ID: a5fdfe58305
Revises: None
Create Date: 2013-11-27 22:44:57.292575

"""

# revision identifiers, used by Alembic.
revision = 'a5fdfe58305'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'futures')
    op.add_column('contracts', sa.Column('inverse_quotes', sa.Boolean(), server_default='false', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'inverse_quotes')
    op.create_table(u'futures',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id'], [u'contracts.id'], name=u'futures_id_fkey'),
    sa.PrimaryKeyConstraint(u'id', name=u'futures_pkey')
    )
    ### end Alembic commands ###
