"""small changes, and change the word user to trader

Revision ID: e0881d53eb6
Revises: 53d28a5cf7e9
Create Date: 2013-07-17 15:48:33.148544

"""

# revision identifiers, used by Alembic.
revision = 'e0881d53eb6'
down_revision = '53d28a5cf7e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('accounted_for', sa.BigInteger(), server_default='0', nullable=True))

    op.alter_column('orders', u'trader_id', new_column_name=u'user_id')
    op.alter_column('positions', u'trader_id', new_column_name=u'user_id')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('orders', u'user_id', new_column_name=u'trader_id')
    op.alter_column('positions', u'user_id', new_column_name=u'trader_id')


    op.drop_column('addresses', 'accounted_for')
    ### end Alembic commands ###
