"""merge ledger branch

Revision ID: 13542ee48bd8
Revises: None
Create Date: 2014-08-18 13:06:54.521783

"""

# revision identifiers, used by Alembic.
revision = '13542ee48bd8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal', u'notes')
    op.add_column('orders', sa.Column('dispatched', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('positions', sa.Column('position_checkpoint', sa.BigInteger(), server_default='0', nullable=True))
    op.add_column('positions', sa.Column('position_cp_timestamp', sa.DateTime(), nullable=True))
    op.add_column('posting', sa.Column('note', sa.String(), nullable=True))
    op.add_column('posting', sa.Column('timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posting', 'timestamp')
    op.drop_column('posting', 'note')
    op.drop_column('positions', 'position_cp_timestamp')
    op.drop_column('positions', 'position_checkpoint')
    op.drop_column('orders', 'dispatched')
    op.add_column('journal', sa.Column(u'notes', sa.VARCHAR(), nullable=True))
    ### end Alembic commands ###
