"""changing trade to store contract

Revision ID: 218cd2d188bd
Revises: 30295579ce49
Create Date: 2013-07-01 11:39:15.901509

"""

# revision identifiers, used by Alembic.
revision = '218cd2d188bd'
down_revision = '30295579ce49'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('contract_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'contract_id')
    ### end Alembic commands ###
