"""make all qty/price columns into BigInteger

Revision ID: 258641a695a4
Revises: 4d6ce83a2737
Create Date: 2014-05-17 15:40:28.989212

"""

# revision identifiers, used by Alembic.
revision = '258641a695a4'
down_revision = '4d6ce83a2737'

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Column, Integer, String, BigInteger, schema, Boolean, sql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
    op.alter_column('contracts', 'tick_size', type_=BigInteger)
    op.alter_column('contracts', 'lot_size', type_=BigInteger)
    op.alter_column('trades', 'quantity', type_=BigInteger)

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
    op.alter_column('contracts', 'tick_size', type_=Integer)
    op.alter_column('contracts', 'lot_size', type_=Integer)
    op.alter_column('trades', 'quantity', type_=Integer)