"""add cold wallet stuff

Revision ID: 4d6ce83a2737
Revises: None
Create Date: 2014-05-15 11:13:45.023028

"""

# revision identifiers, used by Alembic.
revision = '4d6ce83a2737'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('cold_wallet_address', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('hot_wallet_limit', sa.BigInteger(), nullable=True))
    op.drop_column('contracts', u'inverse_quotes')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column(u'inverse_quotes', sa.BOOLEAN(), server_default='false', nullable=False))
    op.drop_column('contracts', 'hot_wallet_limit')
    op.drop_column('contracts', 'cold_wallet_address')
    ### end Alembic commands ###
