"""Add dep/with fees

Revision ID: 5735a01886c2
Revises: None
Create Date: 2014-11-18 11:19:38.557800

"""

# revision identifiers, used by Alembic.
revision = '5735a01886c2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('deposit_base_fee', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('contracts', sa.Column('deposit_bps_fee', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('contracts', sa.Column('withdraw_base_fee', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('contracts', sa.Column('withdraw_bps_fee', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('fee_groups', sa.Column('deposit_factor', sa.Integer(), server_default='100', nullable=False))
    op.add_column('fee_groups', sa.Column('withdraw_factor', sa.Integer(), server_default='100', nullable=False))
    op.alter_column('positions', 'pending_postings',
               existing_type=sa.BIGINT(),
               nullable='False',
               existing_server_default='0::bigint')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'pending_postings',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default='0::bigint')
    op.drop_column('fee_groups', 'withdraw_factor')
    op.drop_column('fee_groups', 'deposit_factor')
    op.drop_column('contracts', 'withdraw_bps_fee')
    op.drop_column('contracts', 'withdraw_base_fee')
    op.drop_column('contracts', 'deposit_bps_fee')
    op.drop_column('contracts', 'deposit_base_fee')
    ### end Alembic commands ###
