#!/bin/bash

# copy over compiled byte-code
cp -r $profile_git_root/dist/build/server $profile_root

# copy over tools
cp $profile_git_root/dist/build/tools/leo.py${profile_pycompiled} $profile_root/tools
cp $profile_git_root/dist/build/tools/generate_new_btc_addresses.py${profile_pycompiled} $profile_root/tools
cp $profile_git_root/dist/build/tools/audit_ledger.py${profile_pycompiled} $profile_root/tools

ln -sf $profile_root/tools/leo.py${profile_pycompiled} $profile_root/tools/leo
ln -sf $profile_root/tools/generate_new_btc_addresses.py${profile_pycompiled} $profile_root/tools/generate_new_btc_addresses
ln -sf $profile_root/tools/audit_ledger.py${profile_pycompiled} $profile_root/tools/audit_ledger

# copy over config
cp $profile_git_root/dist/config/* $profile_conf

# Copy over alembic into tools
cp -r $profile_git_root/dist/alembic $profile_root/tools
ln -sf $profile_conf/alembic.ini $profile_root/tools
mkdir -p $profile_root/tools/alembic/versions
chown -R $profile_user $profile_root/tools/alembic/versions

# copy over keys if they exist
if [ -d $profile_git_root/dist/keys ]; then
   cp $profile_git_root/dist/keys/* $profile_keys
fi

# change permissions
chown -R root:root $profile_root
chmod -R ugo+rX $profile_root
chown -R $profile_user $profile_keys
chmod -R go-rwx $profile_keys
chmod +x $profile_root/server/sputnik/*.py${profile_pycompiled}
chmod +x $profile_root/tools/*.py${profile_pycompiled}

