#!/bin/bash
export PGPASSWORD=$profile_dbmasterpw
psql --host=$profile_dbhost --username=$profile_dbmaster --port=$profile_dbport <<EOF
create database $profile_dbname;
create user $profile_user with password '$profile_dbpassword';
grant all privileges on database $profile_dbname to $profile_user;
EOF

