#!/bin/sh

cp ${base_profile}/res/redirect.conf /etc/apache2/conf-available
sed -e "s|TICKETSERVER_PORT|${profile_ticketserver_port}|" ${base_profile}/res/ticket-server-proxy.conf >/etc/apache2/conf-available/ticket-server-proxy.conf
sed -e "s|RSS_FEED|${profile_exchange_rss_feed}|" ${base_profile}/res/feed-proxy.conf >/etc/apache2/conf-available/feed-proxy.conf

a2enconf redirect
a2enconf ticket-server-proxy
a2enconf feed-proxy
a2enmod ssl
a2enmod rewrite
a2enmod proxy
a2enmod proxy_http

a2dissite 000-default

sed -e "s|SERVER_NAME|${profile_webserver_address}|" ${base_profile}/res/000-default.conf > /etc/apache2/sites-available/sputnik.conf
sed -e "s|KEYS_DIRECTORY|${profile_keys}|" ${base_profile}/res/default-ssl.conf > /etc/apache2/sites-available/sputnik-ssl.conf

a2ensite sputnik.conf
a2ensite sputnik-ssl.conf

service apache2 restart

