#!/bin/bash

cat > $profile_root/dist/launch <<EOF
#!/bin/bash

supervisord -c $profile_conf/supervisor.conf

EOF

chmod +x $profile_root/dist/launch

cat > $profile_root/dist/sctl <<EOF
supervisorctl -c $profile_conf/supervisor.conf \$@

EOF
chmod +x $profile_root/dist/sctl

ln -sf ../tools/leo .

