#!/bin/bash

if [ -n "$UPGRADE" ]; then
    exit 0
fi

cd $profile_conf
cat << EOF | $profile_root/tools/leo 
database init
contracts add BTC
contracts add MXN
contracts add BTC/MXN
contracts modify BTC contract_type cash
contracts modify BTC denominator 100000000
contracts modify MXN contract_type cash
contracts modify MXN denominator 100
contracts modify BTC/MXN contract_type cash_pair
contracts modify BTC/MXN tick_size 100
contracts modify BTC/MXN lot_size 1000000
contracts modify BTC/MXN denominator 1

permissions new Default

accounts add mexbt
accounts add m2
accounts add remainder
accounts add system
accounts modify system default_position_type Asset

accounts add marketmaker
accounts password marketmaker marketmaker
accounts position marketmaker BTC
accounts position marketmaker MXN
accounts add randomtrader
accounts password randomtrader randomtrader
accounts position randomtrader BTC
accounts position randomtrader MXN
EOF

