#!/bin/bash

mkdir -p ${profile_git_root}/dist/clients/www
cd ${profile_git_root}/clients/www

cp -rH templates partials images js css charting_library cldr locale *.coffee index.html ${profile_git_root}/dist/clients/www

