#!/bin/bash

mkdir -p ${profile_git_root}/dist/clients/www
cd ${profile_git_root}/clients/www

cp -rH images js css charting_library cldr locale *.coffee *.html *.css icons ${profile_git_root}/dist/clients/www

