#!/bin/bash

exit 0

if [ -n "$UPGRADE" ]; then
    exit 0
fi

chown $profile_user:$profile_bitcoin_user $profile_conf/bitcoin.conf
chmod 440 $profile_conf/bitcoin.conf

# set bitcoin home and data dir permissions
mkdir -p /data/bitcoind
chown $profile_bitcoin_user:$profile_bitcoin_user /data/bitcoind
chmod 700 /data/bitcoind $profile_bitcoin_root
ln -sf $profile_conf/bitcoin.conf $profile_bitcoin_root/bitcoin.conf

# make .bitcoin dir for sputnik
mkdir -p ~$profile_user/.bitcoin
chown $profile_user:$profile_user $profile_root/.bitcoin
chmod 700 ~$profile_user/.bitcoin
ln -sf $profile_conf/bitcoin.conf $profile_root/.bitcoin

# link supervisor config file
ln -sf $profile_conf/bitcoind.conf /etc/supervisor/conf.d

