#!/bin/bash

# set bitcoin home and data dir permissions
mkdir -p $profile_bitcoin_data
chown $profile_bitcoin_user:$profile_bitcoin_user $profile_bitcoin_data
chmod 700 $profile_bitcoin_data $profile_bitcoin_root
ln -sf $profile_conf/bitcoin.conf $profile_bitcoin_root/bitcoin.conf

USER_HOME=`eval echo ~$profile_user`

# make .bitcoin dir for sputnik
mkdir -p $USER_HOME/.bitcoin
chown $profile_user:$profile_user $USER_HOME/.bitcoin
chmod 700 $USER_HOME/.bitcoin
ln -sf $profile_conf/bitcoin.conf $USER_HOME/.bitcoin

# generate bitcoin password
cd $profile_conf
BITCOIND_PASSWORD=`openssl rand -base64 32 | tr +/ -_`
sed -i "s/\(rpcpassword=\).*/\1$BITCOIND_PASSWORD/" bitcoin.conf

# TODO: Support yes/1/TRUE/etc
if [ "$profile_testnet" = 'true' ]; then
    echo "testnet=1" >> bitcoin.conf
fi

chmod 440 $profile_conf/bitcoin.conf
chown $profile_user:$profile_bitcoin_user $profile_conf/bitcoin.conf

