#!/bin/bash

if [ -n "$UPGRADE" ]; then
    supervisorctl shutdown
    echo "Start supervisor manually once you've done necessary DB migrations"
    echo "$ cd /srv/sputnik/tools; alembic upgrade head"
    echo "$ service supervisor start"
else
    service supervisor restart
fi

