#!/bin/bash

if [ -n "$UPGRADE" ]; then
    supervisorctl shutdown
    touch ${profile_www_root}/maintenance.enable
    echo "Start supervisor manually once you've done necessary DB migrations"
    echo "$ service supervisor start"
    echo "$ rm ${profile_www_root}/maintenance.enable"
else
    service supervisor restart
fi

