#!/bin/bash

if [ -n "$UPGRADE" ]; then
    exit 0
fi

cat << EOF | sudo -u sputnik $profile_root/tools/leo
database init
contracts add BTC
contracts add MXN
contracts add BTC/MXN
contracts modify BTC contract_type cash
contracts modify BTC denominator 100000000
contracts modify MXN contract_type cash
contracts modify MXN denominator 100
contracts modify BTC/MXN contract_type cash_pair
contracts modify BTC/MXN tick_size 100
contracts modify BTC/MXN lot_size 1000000
contracts modify BTC/MXN denominator 1
accounts add marketmaker
accounts password marketmaker marketmaker
accounts add randomtrader
accounts password randomtrader randomtrader
accounts position marketmaker BTC 1000000000
accounts position marketmaker MXN 1000000
accounts position randomtrader BTC 1000000000
accounts position randomtrader MXN 1000000
EOF

