"""Added trade table and some cosmetic modifications

Revision ID: 14af2e19c306
Revises: 218cd2d188bd
Create Date: 2013-07-09 09:33:09.158016

"""

# revision identifiers, used by Alembic.
revision = '14af2e19c306'
down_revision = '218cd2d188bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', u'reference_price',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', u'reference_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
