"""switch denominator from int to bigint

Revision ID: 272edafccba4
Revises: 3f09d56a958a
Create Date: 2013-07-09 11:34:43.767514

"""

# revision identifiers, used by Alembic.
revision = '272edafccba4'
down_revision = '3f09d56a958a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
