"""switch denominator from int to bigint

Revision ID: 3436f7662b04
Revises: 53c36fbefbf7
Create Date: 2013-07-09 11:37:47.675040

"""

# revision identifiers, used by Alembic.
revision = '3436f7662b04'
down_revision = '53c36fbefbf7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('denominato', sa.BigInteger(), server_default='1', nullable=False))
    op.drop_column('contracts', u'denominator')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column(u'denominator', sa.INTEGER(), server_default=u'1', nullable=False))
    op.drop_column('contracts', 'denominato')
    ### end Alembic commands ###
