"""switch denominator from int to bigint

Revision ID: 34951675cc15
Revises: 3436f7662b04
Create Date: 2013-07-09 11:38:06.037290

"""

# revision identifiers, used by Alembic.
revision = '34951675cc15'
down_revision = '3436f7662b04'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('denominator', sa.BigInteger(), server_default='1', nullable=False))
    op.drop_column('contracts', u'denominato')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column(u'denominato', sa.BIGINT(), server_default=u'1::bigint', nullable=False))
    op.drop_column('contracts', 'denominator')
    ### end Alembic commands ###
