"""added cash contract type

Revision ID: 3784386eea87
Revises: 4eb9b769c8c6
Create Date: 2013-07-09 11:41:39.404677

"""

# revision identifiers, used by Alembic.
revision = '3784386eea87'
down_revision = '4eb9b769c8c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
