"""add tick size and image file

Revision ID: 5344e95e7351
Revises: 14af2e19c306
Create Date: 2013-07-09 10:28:44.123247

"""

# revision identifiers, used by Alembic.
revision = '5344e95e7351'
down_revision = '14af2e19c306'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('image_file', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('tick_size', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'tick_size')
    op.drop_column('contracts', 'image_file')
    ### end Alembic commands ###

