"""switch denominator from int to bigint

Revision ID: 53aabe7f2e66
Revises: 57bb64889856
Create Date: 2013-07-09 11:36:46.082760

"""

# revision identifiers, used by Alembic.
revision = '53aabe7f2e66'
down_revision = '57bb64889856'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
