"""switch denominator from int to bigint

Revision ID: 53c36fbefbf7
Revises: 53aabe7f2e66
Create Date: 2013-07-09 11:37:04.881945

"""

# revision identifiers, used by Alembic.
revision = '53c36fbefbf7'
down_revision = '53aabe7f2e66'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('contracts', u'image_file')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column(u'image_file', sa.VARCHAR(), nullable=True))
    op.drop_column('contracts', 'image_url')
    ### end Alembic commands ###
