"""switching price types to biginteger

Revision ID: 53d28a5cf7e9
Revises: 245033b403ff
Create Date: 2013-07-09 14:28:23.298829

"""

# revision identifiers, used by Alembic.
revision = '53d28a5cf7e9'
down_revision = '245033b403ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
      op.alter_column('orders', u'price',
               existing_type=sa.BIGINT(),
               nullable=False)
      op.alter_column('trades', u'price',
               existing_type=sa.BIGINT(),
               nullable=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
