"""make some fields unique and non nullable in Users

Revision ID: aa43764a2fd
Revises: 517d7d27d9c2
Create Date: 2013-07-23 17:03:58.686623

"""

# revision identifiers, used by Alembic.
revision = 'aa43764a2fd'
down_revision = '517d7d27d9c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'futures_contract_info')
    op.alter_column('users', u'login_allowed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=u'false')
    op.alter_column('users', u'nickname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', u'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', u'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', u'nickname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', u'login_allowed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=u'false')
    op.create_table(u'futures_contract_info',
    sa.Column(u'id', sa.INTEGER(), server_default="nextval('futures_contract_info_id_seq'::regclass)", nullable=False),
    sa.Column(u'key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column(u'value', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column(u'contract_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], [u'futures.id'], name=u'futures_contract_info_contract_id_fkey'),
    sa.PrimaryKeyConstraint(u'id', name=u'futures_contract_info_pkey')
    )
    ### end Alembic commands ###
