#!/bin/bash

# copy over compiled byte-code
cp -r $profile_git_root/dist/build/server $profile_root

# copy over tools
cp $profile_git_root/tools/leo.py $profile_root/tools
ln -s $profile_root/tools/leo.py $profile_root/tools/leo

# copy over config
cp $profile_git_root/dist/config/* $profile_conf

# copy over keys
cp $profile_git_root/dist/keys/* $profile_keys

# change permissions
chown -R root:root $profile_root
chmod -R ugo+rX $profile_root
chmod +x $profile_root/server/sputnik/*.py${profile_pycompiled}

