#!/bin/bash

cat << EOF | $profile_root/tools/leo
database init
contracts add BTC
contracts add MXN
contracts add PLN
contracts add HUF

contracts add BTC/MXN
contracts add BTC/PLN
contracts add BTC/HUF

contracts modify BTC contract_type cash
contracts modify BTC denominator 100000000

contracts modify MXN contract_type cash
contracts modify MXN denominator 100

contracts modify PLN contract_type cash
contracts modify PLN denominator 100

contracts modify HUF contract_type cash
contracts modify HUF denominator 100

contracts modify BTC/MXN contract_type cash_pair
contracts modify BTC/MXN tick_size 100
contracts modify BTC/MXN lot_size 1000000
contracts modify BTC/MXN denominator 1

contracts modify BTC/PLN contract_type cash_pair
contracts modify BTC/PLN tick_size 100
contracts modify BTC/PLN lot_size 1000000
contracts modify BTC/PLN denominator 1

contracts modify BTC/HUF contract_type cash_pair
contracts modify BTC/HUF tick_size 100
contracts modify BTC/HUF lot_size 1000000
contracts modify BTC/HUF denominator 1

permissions add Default
EOF


cat << EOF | sudo -u sputnik $profile_root/tools/leo
accounts add customer
accounts add m2
accounts add remainder

accounts add onlinecash
accounts modify onlinecash type Asset

accounts add offlinecash
accounts modify offlinecash type Asset

accounts add depositoverflow
accounts modify depositoverflow type Liability

accounts add pendingwithdrawal
accounts modify pendingwithdrawal type Liability

accounts add marketmaker
accounts password marketmaker marketmaker
accounts position marketmaker BTC
accounts position marketmaker MXN
accounts position marketmaker HUF
accounts position marketmaker PLN
accounts add randomtrader
accounts password randomtrader randomtrader
accounts position randomtrader BTC
accounts position randomtrader MXN
accounts position randomtrader HUF
accounts position randomtrader PLN
admin add admin
EOF


