#!/bin/bash

# this may be a reinstall, so drop the db
# Confirm that we want to drop the db before dropping it!
echo -n "DO YOU WANT TO DROP THE DB: $profile_dbname? "yes" to confirm:" > /dev/tty
read -r </dev/tty
if [[ $REPLY =~ ^yes$ ]]
then
  echo "Dropping DB: $profile_dbname" >/dev/tty
  sudo -u postgres /usr/bin/dropdb -e $profile_dbname
else
  echo "Dropdb waived" >/dev/tty
fi

exit 0

