#!/bin/bash

sudo -u postgres psql <<EOF
create database $profile_dbname;
create user $profile_user with password '$profile_dbpassword';
grant all privileges on database $profile_dbname to $profile_user;
alter role $profile_user with login;
create user pycharm with password 'pycharm';
grant all privileges on database $profile_dbname to pycharm;
EOF

