#!/bin/bash

if [ -n "$UPGRADE" ]; then
    exit 0
fi

# TODO: make sure no one is accessing this and then remove
# /usr/bin/dropdb --if-exists $profile_dbname

sudo -u postgres psql <<EOF
create database $profile_dbname;
create user $profile_user;
grant all privileges on database $profile_dbname to $profile_user;
alter role $profile_user with login;
create user pycharm with password 'pycharm';
grant all privileges on database $profile_dbname to pycharm;
EOF

