#!/bin/bash

cat << EOF | $profile_root/tools/leo 
database init
contracts add BTC
contracts add MXN
contracts add PLN
contracts add HUF

contracts add BTC/MXN
contracts add BTC/PLN
contracts add BTC/HUF

contracts add NETS2014
contracts set NETS2014 contract_type prediction
contracts set NETS2014 denominator 1000
contracts set NETS2014 lot_size 1000000
contracts set NETS2014 tick_size 1
contracts set NETS2014 expiration 2014-06-28
contracts set NETS2014 denominated_contract_ticker BTC

contracts add NETS2015
contracts set NETS2015 contract_type prediction
contracts set NETS2015 denominator 1000
contracts set NETS2015 lot_size 1000000
contracts set NETS2015 tick_size 1
contracts set NETS2015 expiration 2015-06-28
contracts set NETS2015 denominated_contract_ticker BTC

contracts set BTC contract_type cash
contracts set BTC denominator 100000000
contracts set BTC hot_wallet_limit 1000000000
contracts set BTC cold_wallet_address XXX

contracts set MXN contract_type cash
contracts set MXN denominator 10000

contracts set PLN contract_type cash
contracts set PLN denominator 10000

contracts set HUF contract_type cash
contracts set HUF denominator 100

contracts set BTC/MXN contract_type cash_pair
contracts set BTC/MXN tick_size 100
contracts set BTC/MXN lot_size 1000000
contracts set BTC/MXN denominator 1
contracts set BTC/MXN denominated_contract_ticker MXN
contracts set BTC/MXN payout_contract_ticker BTC

contracts set BTC/PLN contract_type cash_pair
contracts set BTC/PLN tick_size 100
contracts set BTC/PLN lot_size 1000000
contracts set BTC/PLN denominator 1
contracts set BTC/PLN denominated_contract_ticker PLN
contracts set BTC/PLN payout_contract_ticker BTC

contracts set BTC/HUF contract_type cash_pair
contracts set BTC/HUF tick_size 100
contracts set BTC/HUF lot_size 1000000
contracts set BTC/HUF denominator 1
contracts set BTC/HUF denominated_contract_ticker HUF
contracts set BTC/HUF payout_contract_ticker BTC

permissions add Default login
permissions add Full trade withdraw deposit login
permissions add NoTrade withdraw deposit login
EOF

cat << EOF | $profile_root/tools/leo
accounts add customer
accounts add m2
accounts add remainder

accounts add onlinecash
accounts set onlinecash type Asset

accounts add offlinecash
accounts set offlinecash type Asset

accounts add depositoverflow
accounts set depositoverflow type Liability

accounts add pendingwithdrawal
accounts set pendingwithdrawal type Liability

accounts add adjustments
accounts set adjustments type Asset

accounts add marketmaker
accounts password marketmaker marketmaker
accounts position marketmaker BTC
accounts position marketmaker MXN
accounts position marketmaker HUF
accounts position marketmaker PLN
accounts add randomtrader
accounts password randomtrader randomtrader
accounts position randomtrader BTC
accounts position randomtrader MXN
accounts position randomtrader HUF
accounts position randomtrader PLN
admin add admin
EOF

