#!/bin/bash

cat << EOF | $profile_root/tools/leo 
database init
contracts add BTC
contracts add MXN
contracts add PLN
contracts add HUF

contracts add BTC/MXN
contracts add BTC/PLN
contracts add BTC/HUF

contracts add NETS2014
contracts set NETS2014 contract_type prediction
contracts set NETS2014 denominator 1000
contracts set NETS2014 lot_size 1000000
contracts set NETS2014 tick_size 1
contracts set NETS2014 expiration 2014-06-28
contracts set NETS2014 denominated_contract_ticker BTC
contracts set NETS2014 payout_contract_ticker NETS2014
contracts set NETS2014 description "Nets win in 2014"
contracts set NETS2014 fees 200

contracts add NETS2015
contracts set NETS2015 contract_type prediction
contracts set NETS2015 denominator 1000
contracts set NETS2015 lot_size 1000000
contracts set NETS2015 tick_size 1
contracts set NETS2015 expiration 2015-06-28
contracts set NETS2015 denominated_contract_ticker BTC
contracts set NETS2015 payout_contract_ticker NETS2015
contracts set NETS2015 description "Nets win in 2015"
contracts set NETS2015 fees 200

contracts add BULLS2015
contracts set BULLS2015 contract_type prediction
contracts set BULLS2015 denominator 1000
contracts set BULLS2015 lot_size 1000000
contracts set BULLS2015 tick_size 1
contracts set BULLS2015 expiration 2015-06-28
contracts set BULLS2015 denominated_contract_ticker BTC
contracts set BULLS2015 payout_contract_ticker BULLS2015
contracts set BULLS2015 description "Bulls win in 2015"
contracts set BULLS2015 fees 200

contracts set BTC contract_type cash
contracts set BTC denominator 100000000
contracts set BTC hot_wallet_limit 1000000000
contracts set BTC cold_wallet_address XXX
contracts set BTC deposit_instructions "Please deposit your crypto-currency to the below address"

contracts set MXN contract_type cash
contracts set MXN denominator 10000
contracts set MXN deposit_instructions "Please mail a check to us\n\n500 Westover Dr #4673\nSanford NC 22370\n\nAnd reference the address in the memo field"

contracts set PLN contract_type cash
contracts set PLN denominator 10000
contracts set PLN deposit_instructions "Please mail a check to us\n\n500 Westover Dr #4673\nSanford NC 22370\n\nAnd reference the address in the memo field"


contracts set HUF contract_type cash
contracts set HUF denominator 100
contracts set HUF deposit_instructions "Please mail a check to us\n\n500 Westover Dr #4673\nSanford NC 22370\n\nAnd reference the address in the memo field"

contracts set BTC/MXN contract_type cash_pair
contracts set BTC/MXN tick_size 100
contracts set BTC/MXN lot_size 1000000
contracts set BTC/MXN denominator 1
contracts set BTC/MXN denominated_contract_ticker MXN
contracts set BTC/MXN payout_contract_ticker BTC
contracts set BTC/MXN fees 100

contracts set BTC/PLN contract_type cash_pair
contracts set BTC/PLN tick_size 100
contracts set BTC/PLN lot_size 1000000
contracts set BTC/PLN denominator 1
contracts set BTC/PLN denominated_contract_ticker PLN
contracts set BTC/PLN payout_contract_ticker BTC
contracts set BTC/PLN fees 100

contracts set BTC/HUF contract_type cash_pair
contracts set BTC/HUF tick_size 100
contracts set BTC/HUF lot_size 1000000
contracts set BTC/HUF denominator 1
contracts set BTC/HUF denominated_contract_ticker HUF
contracts set BTC/HUF payout_contract_ticker BTC
contracts set BTC/HUF fees 100

permissions add Default login
permissions add Full trade withdraw deposit login
permissions add NoTrade withdraw deposit login

fees add Default 100 100
fees add NoFee 0 0
fees add LiqProvider 100 0
EOF

cat << EOF | $profile_root/tools/leo
accounts add customer
accounts add m2
accounts add remainder
accounts set customer fees NoFee
accounts set m2 fees NoFee

accounts add onlinecash
accounts set onlinecash type Asset

accounts add offlinecash
accounts set offlinecash type Asset

accounts add depositoverflow
accounts set depositoverflow type Liability

accounts add pendingwithdrawal
accounts set pendingwithdrawal type Liability

accounts add adjustments
accounts set adjustments type Asset

accounts add marketmaker
accounts password marketmaker marketmaker
accounts position marketmaker BTC
accounts position marketmaker MXN
accounts position marketmaker HUF
accounts position marketmaker PLN
accounts add randomtrader
accounts password randomtrader randomtrader
accounts position randomtrader BTC
accounts position randomtrader MXN
accounts position randomtrader HUF
accounts position randomtrader PLN
admin add admin
EOF

