#!/bin/bash

# create the logs directory
mkdir -p $profile_logs

# chat.log needs to be readable/writable by sputnik
touch $profile_logs/chat.log
chown $profile_user:$profile_user $profile_logs/chat.log
chmod 660 $profile_logs/chat.log

