#!/bin/sh

. ./install-tools

: > ./install.log
export LOGFILE=`readlink -e ./install.log`

if [ $# -ne 2 ]; then
    echo "Usage: $0 profile root" 1>&2
    exit 1
fi

export PROFILE=$1
export ROOT=$2

if [ ! -d profiles/$PROFILE ]; then
    echo "Profile '$PROFILE' not found." 1>&2
    exit 1
fi

log "Installing sputnik profile '$PROFILE'..."

cd profiles/$PROFILE

run_scripts pre-install

check_dependencies dpkg
check_dependencies source
check_dependencies python

run_scripts install
run_scripts post-install

cd ../..

log "Install complete."

