#!/bin/bash

sudo -u postgres psql <<EOF
create database sputnik;
create user $profile_user;
grant all privileges on database sputnik to $profile_user;
alter role $profile_user with login;
create user pycharm with password 'pycharm';
grant all privilieges on database sputnik to pycharm;
EOF

