#!/bin/bash

if [ -n "$UPGRADE" ]; then
    exit 0
fi

# set bitcoin home and data dir permissions
mkdir -p $profile_bitcoin_data
chmod 700 $profile_bitcoin_data $profile_bitcoin_root
ln -sf $profile_conf/bitcoin.conf $profile_bitcoin_root/bitcoin.conf

