#!/bin/bash

sudo -u sputnik /bin/bash <<EOF
/srv/sputnik/tools/leo database init
/srv/sputnik/tools/leo contracts add BTC
/srv/sputnik/tools/leo contracts add MXN
/srv/sputnik/tools/leo contracts add MXN/BTC
/srv/sputnik/tools/leo contracts modify BTC contract_type cash
/srv/sputnik/tools/leo contracts modify BTC denominator 100000000
/srv/sputnik/tools/leo contracts modify MXN contract_type cash
/srv/sputnik/tools/leo contracts modify MXN denominator 100
/srv/sputnik/tools/leo contracts modify MXN/BTC contract_type cash_pair
/srv/sputnik/tools/leo contracts modify MXN/BTC tick_size 100
/srv/sputnik/tools/leo contracts modify MXN/BTC lot_size 1000000
/srv/sputnik/tools/leo contracts modify MXN/BTC denominator 100
EOF
